#!/bin/sh
set -e

: "${AWS_DEFAULT_REGION:?Need to set AWS_DEFAULT_REGION in container environment}"

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND
